Feature/#2
meopin-top/convey-your-mind-WSS pull request #9
Opened 2023-08-13 12:37 UTC by j1mmyson

## 개요
WSS 주요 핵심 기능 및 전체적인 코드 틀 구현

## 내용
- Redis 연결 및 통신 구현
- 브로드캐스팅 구현
- Go Clean Architecture 적용 (새로 배워온 개념이라 아직 부족..)

2023-08-14 05:21 UTC, mochang2 commented
구글에 열심히 검색해봤는데... Go를 잘 몰라서 각 파일이 무슨 역할을 하는지 잘 모르겠어요.
각 파일이 어떤 목적으로 선언됐는지, 왜 타입만 선언된 파일들도 있는지 설명해주실 수 있나요?

2023-08-14 09:23 UTC, mochang2 commented on meopin/delivery/meopin_handler.go
> +		}
`WebsocketConnection` 함수의 이 부분까지가 `main.go`와 똑같은데 공통 함수로 분리할 수 있지 않을까요?

2023-08-14 09:23 UTC, mochang2 commented on meopin/repository/redis/redis_meopin.go
> +package redis
상위 디렉터리가 redis니까 이 파일에는 `redis_` prefix가 없어도 될 것 같습니다.

2023-08-14 09:23 UTC, mochang2 commented on meopin/repository/redis/redis_meopin.go
> +}
이거는 go를 잘 몰라서... 그럴 수 있는데 `GetInstance`랑 `NewDatabase`랑 하는 역할의 차이가 뭐에요?
singleton이면 결국 둘이 하는 역할이 같은 거 아닌가요?

2023-08-14 09:23 UTC, mochang2 commented on meopin/repository/redis/redis_meopin.go
> +	}
`GetAndAdd`가 `Get`이랑 겹치는 로직을 `GetAndAdd`에서 `Get`을 호출하게 수정할 수 없나요?

2023-08-14 09:23 UTC, mochang2 commented on meopin/usecase/paper_usecase.go
> +
필요 없는 공백 같아요.
이건 지극히 개인적인 생각으로 공백도 컨벤션이라고 생각해서 ㅎㅎ

2023-08-14 09:23 UTC, mochang2 commented on meopin/delivery/middleware/middleware.go
> +
프로젝트에 이 미들웨어 하나만 있을 거 같으면 굳이 디렉터리를 만든 다음에 디렉터리와 같은 이름의 파일이 필요하진 않을 거 같습니다.
나눈 이유가 있을까요?

2023-08-14 09:27 UTC, mochang2 requested changes
request changes로 바꿀게요~

2023-08-14 11:47 UTC, j1mmyson commented on meopin/delivery/meopin_handler.go
> +		}
아이고 구현 해놓고 메인함수에 적용을 안해놨네요
다음 커밋에 적용 해놓겠습니다~

2023-08-14 12:10 UTC, j1mmyson commented
> 구글에 열심히 검색해봤는데... Go를 잘 몰라서 각 파일이 무슨 역할을 하는지 잘 모르겠어요. 각 파일이 어떤 목적으로 선언됐는지, 왜 타입만 선언된 파일들도 있는지 설명해주실 수 있나요?

우선 요 레포 보고 아키텍처 설계했습니다
=> https://github.com/bxcodec/go-clean-arch

레이어가 크게 4가지로 나뉘는데요 가장 큰 특징은 하위 레이어는 상위 레이어에 호출될 수 없다는 점입니다.
domain > repository > usecase > delivery
(ex. 모든 레이어에서 domain 호출 가능, domain 레이어에서는 다른 레이어 호출 불가능)

- domain
  - 모든 레이어에 쓰일 객체가 구현되는 부분
  - struct, interface로 주로 구현됨
- repository
  - 외부 종속성을 다루는 객체를 구현
  - 주로 DB와 같은 것들을 다루는 구현부
- usecase
  - 서비스의 메인 프로세스가 구현되는 부분
  - 머핀탑으로 치면 브로드캐스팅 기능
- delivery
  - 서비스에서 만들어진 결과를 클라이언트에게 제공해주는 레이어
  - REST API, HTML File, gRPC같은 딜리버리 타입이 구현되는 부분
  - 데이터를 수신하는 로직도 이 레이어에서 구현됨

위에가 각 폴더의 목적입니다.

타입만 구현되어있는 코드는 고언어의 특징중 하나인 덕타이핑 개념을 녹였는데요
덕타이핑 = "어떤 객체가 Quack(). Walk()라는 메서드를 갖고 있으면 이 객체를 Duck이라고 하겠어" 입니다.
그래서 선언부는 domain 패키지에, 구현부는 usecase, repository 패키지에서 구현하여 확장성을 높이고 결합도를 낮춰보려고 이렇게 코드를 짰습니다

덕타이핑에 대해 잘 설명된 글을 하나 첨부하겠슴다
https://www.popit.kr/golang%EC%9C%BC%EB%A1%9C-%EB%A7%8C%EB%82%98%EB%B3%B4%EB%8A%94-duck-typing/

2023-08-27 12:34 UTC, j1mmyson commented on meopin/repository/redis/redis_meopin.go
> +}
`GetInstance`는 싱글톤 객체 불러오는 함수고 `NewDatabase`는 새로운 인스턴스를 생성하는 함수인데 현재는 `GetInstance`만 사용중입니다. 개발하다가 호출할 필요가 없다고 생각들면 `NewDatabase`는 삭제할 예정입니다

2023-08-27 12:35 UTC, j1mmyson commented on meopin/repository/redis/redis_meopin.go
> +	}
음 이부분은,, 같은 레벨의 메소드에서 다른 메소드를 호출하는게 좋을지 잘 모르겠습니다. 좀 더 생각해보겠습니다

2023-08-27 12:40 UTC, j1mmyson commented on meopin/delivery/middleware/middleware.go
> +
고에서는 패키지명을 폴더 이름과 동일하게 지어주는데요, `delivery.checkWebsocket()`와 같이 사용하는 것 보단 `middleware.checkWebsocket()`으로 불러오는게 더 좋을것 같아서 폴더에 생성하였습니다

2023-08-27 13:41 UTC, mochang2 commented on meopin/repository/redis/redis_meopin.go
> +	}
어차피 두 개밖에 없어서 당장에 꼭 리팩토링이 필요한 부분은 아니긴 합니다. ㅎㅎ

2023-08-27 13:43 UTC, mochang2 commented on meopin/delivery/middleware/middleware.go
> +
패키지명과 폴더 이름을 동일하게 지어줘야만 인식이 되나요? 아님 컨벤션이라는 말씀인가요??

만약 다른 미들웨어가 필요하면 파일 이름을 어떻게 설정하나요??

2023-08-27 13:43 UTC, mochang2 approved these changes

2023-09-11 12:32 UTC, merged